name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Verify Terraform (use pre-installed version on self-hosted runner)
      - name: Verify Terraform
        run: terraform -v

      # Step 3: Azure Login (OIDC)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 4: Terraform Init
      - name: Terraform Init
        working-directory: ./Dev
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        working-directory: ./Dev
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        working-directory: ./Dev
        run: terraform plan

      # Step 7: Terraform Apply (only for main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./Dev
        run: terraform apply -auto-approve
